// ---------------------------------------------------------------------------
// Lantern, shared domain types
// The whole product is a loop:  seed phrases  →  induce structure  →
// generate lessons  →  learn  →  contribute more  →  (repeat, better).
// These types are the contract between the engine, the store, and the UI.
// ---------------------------------------------------------------------------

export type LanguageStatus =
  | "vulnerable"
  | "definitely-endangered"
  | "severely-endangered"
  | "critically-endangered"
  | "dormant";

export type ScriptKind = "latin" | "syllabary";

export type Confidence = "high" | "medium" | "low";

/** A language Lantern is helping keep alight. */
export interface Language {
  id: string; // slug used in URLs + as a key, e.g. "mi", "chr"
  name: string; // English name, e.g. "Māori"
  endonym: string; // name in the language, e.g. "te reo Māori"
  iso639: string; // ISO 639 code
  status: LanguageStatus;
  region: string;
  speakers: string; // human-readable, e.g. "~50,000 first-language"
  color: string; // accent hex used across the Ark
  script: ScriptKind;
  blurb: string; // one sentence on why it matters
  ttsLang?: string; // BCP-47 hint for the Web Speech API, e.g. "mi-NZ"
  featured?: boolean;
}

/**
 * A seed item: a phrase + its meaning, contributed by a speaker (or loaded
 * from a verified, cited corpus). This is the GROUND TRUTH the engine reasons
 * over, the engine never invents words outside what these phrases attest.
 */
export interface Phrase {
  id: string;
  languageId: string;
  target: string; // the phrase in correct orthography
  romanization?: string; // Latin transliteration (used for syllabary scripts)
  english: string;
  gloss?: string; // interlinear gloss (may be human- or AI-supplied)
  category: string; // greeting | everyday | number | family | sentence | ...
  audioUrl?: string; // speaker-recorded pronunciation (Vercel Blob URL)
  source?: string; // citation for trust
  confidence: Confidence;
  contributedBy: string; // "seed" or a contributor handle
  createdAt: number;
}

/** A word/morpheme the engine extracted and aligned to a meaning. */
export interface VocabItem {
  id: string;
  languageId: string;
  form: string;
  meaning: string;
  pos?: string; // hypothesized part of speech
  notes?: string;
  confidence: Confidence;
  evidence: string[]; // ids of phrases that attest this item
  // True only if every non-gap token of `form` actually occurs in one of its
  // cited evidence phrases. Unverified vocab is kept (it may be a real
  // segmentation guess) but is NOT trusted as ground truth by the guardrail.
  verified?: boolean;
}

/** A grammatical regularity the engine hypothesized from minimal pairs. */
export interface Pattern {
  id: string;
  languageId: string;
  label: string; // e.g. "kua, perfective / completed-action marker"
  description: string; // plain-language explanation
  examples: string[]; // short illustrative strings drawn from the corpus
  confidence: Confidence;
}

/** One study card. */
export interface Flashcard {
  id: string;
  prompt: string; // shown first (English)
  answer: string; // the target-language form
  romanization?: string;
  hint?: string;
  category?: string;
}

/**
 * A practice sentence the engine GENERATED by recombining KNOWN vocab and
 * patterns only. `usesVocab` lists the vocab forms it relies on, every one
 * must already exist in the induced vocab bank (the no-hallucination contract).
 */
export interface PracticeSentence {
  target: string;
  english: string;
  usesVocab: string[];
  note?: string;
}

/** A generated mini-course for a language. */
export interface Lesson {
  id: string;
  languageId: string;
  title: string;
  intro: string;
  cards: Flashcard[];
  practice: PracticeSentence[];
  createdAt: number;
}

/** The full output of one induction run over a language's corpus. */
export interface InductionResult {
  languageId: string;
  vocab: VocabItem[];
  patterns: Pattern[];
  lesson: Lesson;
  corpusSize: number; // how many phrases the run reasoned over
  generatedAt: number;
  model: string;
  source: "ai" | "fixture"; // was this real AI inference or a cached fallback?
}

/** Lightweight stats powering the Living Ark dashboard + live counters. */
export interface ArkStats {
  languages: number;
  phrases: number;
  vocab: number;
  contributions: number;
  recentContributions: { languageId: string; at: number }[];
}
